### ISSUE TITLE
Sigue como activo el direccionamiento de SANOFI cuando debe de estar desactivado.

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#10]
Favor de desactivarlo

**Comment by Luart125125New** [comment]
@ItzelCervera que cuenta tiene SANOFI !?

**Comment by ItzelCervera** [comment]
mxsanofiredir @Luart125125New

**Comment by Luart125125New** [comment]
Notas: la cuenta **mxsanofiredir** no se encuentra en la tabla **redireccionamiento_conteo_trafico** y su ultima publicación fue al rededor del 2009.

**Comment by ItzelCervera** [comment]
@Luart125125New ¿Podrías revisar porque aparece en este reporte por favor? Ya que no es correcto. 
![image](https://user-images.githubusercontent.com/67603333/88100555-4c909a00-cb62-11ea-9908-5dcb53dd6431.png)

**Comment by PaLberto21** [comment]
@Luart125125New esta incidencia ya quedo resuelta? gracias
