### ISSUE TITLE
Favor de validar vacante que no se visualiza de givaudan

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#106]

**Comment by MitziMtz** [comment]
@ItzelCervera Ya revise los archivos procesados del cliente y no se encontré un archivo con alguna vacante y en el WS revise las peticiones desde el día 22 y no hay una que corresponda al cliente.

**Comment by ItzelCervera** [comment]
Gracias, le comento al cliente
