### ISSUE TITLE
Favor de generar direccionamiento FTp xmxdofiscalredirx 

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#107]

**Comment by Luart125125New** [comment]
Ya se solicitaron las credenciales para el nuevo cliente, estaremos atentos a cualquier comentario por parte de infra y cualquier comentario se notificara.

**Comment by Luart125125New** [comment]
Host name: direccionamiento.occ.com.mx
User: xmxdofiscalredirx
Pass: dn/M2nwF6\Pj3Z>\

**Comment by ItzelCervera** [comment]
MIl gracias!!
