### ISSUE TITLE
Cliente de Universidad Rioja sigue sin poder acceder (Equest) al uso de su direccionamiento

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#11]
Necesitan usuario y contraseña del direccionamiento.

**Comment by PaLberto21** [comment]
@ItzelCervera sería importante conocer el horario en que Equest envía las vacantes del cliente a nuestro repositorio para saber de nuestra parte en que momento programar el proceso, gracias

**Comment by ItzelCervera** [comment]
Si gracias, en cuanto recibamos la solicitud de conferencia o los horarios con gusto les aviso.
