### ISSUE TITLE
Favor de actualizar scrapping de Zurich, cambio url de donde estan sus vacantes

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#110]
https://careers.zurich.com/?locale=es_ES

**Comment by Luart125125New** [comment]
Su proceso ya se ha actualizado, esperamos la aprobación para subir los cambios a productivo, por el momento el proceso ya se encuentra scrapeando la pagina de forma local y los resultados ya se pueden ver en el portal de OCC.

**Comment by ItzelCervera** [comment]
Muchas gracias!!
