### ISSUE TITLE
Favor de validar scrapping de Amazon por favor

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#111]
https://www.amazon.jobs/en/jobs/SF210055473/seasonal-virtual-customer-service-associate-mexico-city-monterrey-guadalajara

**Comment by Luart125125New** [comment]
Al parecer si es factible scrapear la pagina de amazon el cual usaríamos la siguiente URL: https://www.amazon.jobs/en/search?base_query=&loc_query=Mexico&country=MEX

**Comment by ItzelCervera** [comment]
Gracias!
