### ISSUE TITLE
Favor validar scrapping de cliente Verato.

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#112]
https://verato.com/company/careers/ 
CRM: https://www.paylocity.com/

**Comment by Luart125125New** [comment]
Las 2 urls se pueden scrapear.
Con respecto a la primera URL (https://verato.com/company/careers/) usariamos esta para extraer las vacantes de solo México https://recruiting.paylocity.com/Recruiting/Jobs/All/321e2834-a8f2-441e-a825-26d865ffdc13?location=MEXICO&department=All%20Departments. Si se puede scrappear.
 
Con respeto a  https://www.paylocity.com/ (CRM)  revise su pagina ( https://www.paylocity.com/careers/career-opportunities/all-listings/? ) y no tiene vacantes en México tal vez lo que podríamos usar serian las vacantes que dicen de forma remota. Y si se puede scrapear esta pagina

**Comment by ItzelCervera** [comment]
Mil gracias Raúl!
