### ISSUE TITLE
Favor de generar credenciales para direccionamiento nuevo de Hitch

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#117]
Usuario: xmxhitch3643redirx
Webservice

**Comment by Luart125125New** [comment]
Ya revise la cuenta y no detecto alguna anormalidad. Ya se le puede entregar la cuenta al usuario para que le asignen un paquete y se disponga de créditos para realizar la fase de pruebas de su servicio.

**Comment by ItzelCervera** [comment]
Gracias
