### ISSUE TITLE
Favor de validar scrapping https://careers.calii.com/

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#118]

**Comment by Luart125125New** [comment]
No puedo validar la pagina ya que no hay vacantes y no puedo ver la estructura de las vacantes.

![image](https://user-images.githubusercontent.com/53098943/118310126-cdcf6980-b4b3-11eb-8ff6-d82ded92071b.png)

**Comment by ItzelCervera** [comment]
gracias
