### ISSUE TITLE
Revisión de funcionamiento de cuentas de direccionamiento

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#12]
Favor de revisar la cuenta de xmxventramexredirx ya que no cuenta con vacantes desde junio (Scrapping)

**Comment by PaLberto21** [comment]
El link para el servicio del cliente es:  https://empleos.flex-n-gate.com/jobs  y se presenta solo una vacante que se esta publicando en nuestro portal de forma correcta

![image](https://user-images.githubusercontent.com/44237843/87969837-78d7e800-ca88-11ea-9a03-3ce824a5527c.png)



![image](https://user-images.githubusercontent.com/44237843/87969726-4928e000-ca88-11ea-86db-dfae6c8087aa.png)

**Comment by ItzelCervera** [comment]
Gracias
