### ISSUE TITLE
Favor de desactivar direccionamiento de Hella

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#121]
![image](https://user-images.githubusercontent.com/67603333/118543716-3f105600-b71a-11eb-861d-70fce7321868.png)

**Comment by Luart125125New** [comment]
Listo @ItzelCervera , me puedes apoyar a validar la desactivación.

**Comment by ItzelCervera** [comment]
Gracias!!
