### ISSUE TITLE
Favor de validar scrapping de https://careers.posadas.com/go/Vacantes

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#123]

**Comment by Luart125125New** [comment]
Si se puede Scrapear la pagina solo que la url que nos dieron ya es incorrecta, usaríamos la siguiente url para scrapear la pagina https://careers.posadas.com/go/Vacantes/513219/

**Comment by ItzelCervera** [comment]
Gracias!!
