### ISSUE TITLE
Favor de desactivar direccionamiento xmxsftwronex 

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#124]
![image](https://user-images.githubusercontent.com/67603333/118851887-dbac3280-b897-11eb-90dc-dd92d9f24d6d.png)

**Comment by Luart125125New** [comment]
Listo @ItzelCervera , me puedes apoyar a validar la desactivación.

**Comment by ItzelCervera** [comment]
Muchas gracias =)
