### ISSUE TITLE
Favor de validar scrapping de https://jobs.issworld.com/search/?createNewAlert=false&q=&locationsearch=mexico&optionsFacetsDD_customfield1=&optionsFacetsDD_customfield2=&optionsFacetsDD_customfield3=

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#127]
https://jobs.issworld.com/search/?createNewAlert=false&q=&locationsearch=mexico&optionsFacetsDD_customfield1=&optionsFacetsDD_customfield2=&optionsFacetsDD_customfield3=

**Comment by Luart125125New** [comment]
@ItzelCervera  la pagina no cuenta con vacantes en México pero basándome en sus publicaciones globales, si se puede scraperar, para confirmar y validar que no hay cambios con las vacantes en México es necesario solicitar que publiquen una vacante en México para poner a prueba el proceso creado.

**Comment by ItzelCervera** [comment]
gracias!
