### ISSUE TITLE
Favor de validar direccionamiento Scrapping https://talento.christus.mx/

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#13]

**Comment by PaLberto21** [comment]
@MitziMtz nos apoyas con la validación porfa, muchas gracias

**Comment by MitziMtz** [comment]
@PaLberto21 @ItzelCervera Buenas tardes, ya valide la pagina y es factible por scrapping

**Comment by ItzelCervera** [comment]
Gracias
