### ISSUE TITLE
Favor de validar scrapping www.webasto-career.com

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#130]

**Comment by Luart125125New** [comment]
Si es factible Scrapear la pagina y usaríamos la siguiente url para obtener las vacantes https://jobs.webasto.com/search/?createNewAlert=false&q=Mexico&optionsFacetsDD_country=&optionsFacetsDD_location=&optionsFacetsDD_dept=&optionsFacetsDD_shifttype=

**Comment by ItzelCervera** [comment]
gracias!!
