### ISSUE TITLE
Favor de validar scrapping https://giga.hiringroom.com/jobs

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#132]
El cliente tiene webservice pero hay muchos problemas.

https://career19.sapsf.com/career?company=bocarsadec&career%5fns=job%5flisting%5fsummary&navBarLevel=JOB%5fSEARCH&_s.crb=vkePq%2fkDLVICy46lyEkGiJH7LNQq622W2h6wumDPcNg%3d

**Comment by Luart125125New** [comment]
Mientras la pagina se mantenga de la misma manera al momento de la evaluación, si se puede Scrapear.

**Comment by ItzelCervera** [comment]
gracias
