### ISSUE TITLE
Favor de generar credenciales de direccionamiento webservice de cliente xmxventuressof232red

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#134]

**Comment by Luart125125New** [comment]
Acabo de revisar su información y no parece haber alguna anormalidad. La cuenta se ve bien.

**Comment by ItzelCervera** [comment]
Gracias, entonces me apoyas con las credenciales pf?

**Comment by Luart125125New** [comment]
Yo ya no tengo acceso a sus credenciales.

**Comment by ItzelCervera** [comment]
ok gracias!
