### ISSUE TITLE
Favor de validar Scrapping de cliente    https://ancabe.orangehrmlive.com/recruitmentApply/3/view  

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#136]
https://ancabe.orangehrmlive.com/recruitmentApply/3/view

**Comment by Luart125125New** [comment]
La pagina si se puede Scrappear pero hay varios detalles que se tienen que aclarar para confirma si el servicio por scrapper es factible.
- En su pagina principal donde se encuentran las vacantes disponibles no hay una URL designada para la vacante en especifico, lo mas que podemos hacer es  dirigir al usuario directamente al formulario de la vacante (Cosa que no solemos hacer ya que los usuarios suelen revisar la información directamente de la vacante en la pagina del cliente), pero para poder realizar esta acción.
- Para poder confirmar que la pagina es 100% factible scrapearla, tenemos que tener otra vacante para poder validar nuestras observaciones y confirmar el  proceso (Se requiere que al momento de validar la pagina cuente con 2 o mas vacantes disponibles).
- El principal detalle por el cual recomiendo una mayor observación y precaución al validar esta pagina es que la estructura de las urls son muy simples y a no ser que la pagina literalmente es nueva y solo ha publicado 2 vacantes (esto al momento de la revisión de la pagina) o el otro caso es que estarían reiniciando sus ids en las vacantes el cual podría llegar afectar el servicio ya sea al momento de redirigir a los clientes o con un servicio interno al momento de scrapearlas causaría un fallo en el proceso.

**Comment by ItzelCervera** [comment]
Muchas gracias por la revision @Luart125125New
