### ISSUE TITLE
Favor de validar scrapping de https://careers.velatia.com/jobs/1225534-profesional-de-comercio-exterior

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#138]
Universidad de Rioja cambiara de ATS

**Comment by Luart125125New** [comment]
Si se puede scrapear la pagina, se usaría la siguiente url https://careers.velatia.com/jobs?location=IKUSI+Mexico para obtener las vacantes.

**Comment by ItzelCervera** [comment]
Gracias!
