### ISSUE TITLE
Publicaciones de Ruba FTP

### ISSUE THREAD

**Issue by PaLberto21** [occmundial/VAPS-Requirements-Bugs#14]
@Luart125125New @MitziMtz nos apoyan a revisar el proceso de publicación para el cliente, anexo xml, gracias!

`<?xml version="1.0" encoding="UTF-8"?>

<PublicacionOfertas>

  <AgregarOferta>

    <DateExpires>2020-08-03</DateExpires>

    <JobTitle>SUPERVISOR DE CONSTRUCCION DE VIVIENDA</JobTitle>

    <JobBody>Supervisar y dirigir la construcción de viviendas de acuerdo a los manuales de procesos, supervisión y control de obra de la empresa, en los desarrollos habitacionales con el objeto de lograr la más alta calidad y concluirlo en tiempo.</JobBody>

    <JobLocationID>301</JobLocationID>

    <ShowContactInfo>0</ShowContactInfo>

    <ContactCompanyName>RUBA</ContactCompanyName>

    <ContactEmailAddress>

    </ContactEmailAddress>

    <ContactPhoneNumber>

    </ContactPhoneNumber>

    <ContactFaxNumber>

    </ContactFaxNumber>

    <ContactStreetAddress>

    </ContactStreetAddress>

    <ContactCity>

    </ContactCity>

    <ContactState>

    </ContactState>

    <ContactPostalCode>

    </ContactPostalCode>

    <SalaryFrom>0</SalaryFrom>

    <SalaryTo>0</SalaryTo>

    <SalaryTime>0</SalaryTime>

    <JobRefCode>req241</JobRefCode>

    <JobTypeFullTime>1</JobTypeFullTime>

    <JobTypePartTime>0</JobTypePartTime>

    <JobTypeContract>0</JobTypeContract>

    <JobTypePermanent>1</JobTypePermanent>

    <ContactName>

    </ContactName>

    <JobCity>

    </JobCity>

    <JobFunctionID>70</JobFunctionID>

    <JobLevelID>3</JobLevelID>

    <CompanyTurn>

    </CompanyTurn>

    <URLExterno>https://ruba.csod.com/ux/ats/careersite/1/home/requisition/241?c=ruba</URLExterno>

  </AgregarOferta>

  <AgregarOferta>

    <DateExpires>2020-08-24</DateExpires>

    <JobTitle>INGENIERO DE PRUEBAS/QA TESTER</JobTitle>

    <JobBody>

      <p style="text-align: justify;">Analizar, diseñar y ejecutar las pruebas de Software, para impulsar los nuevos proyectos de la empresa, con el fin de eficientar la calidad en la operación de los mismos.</p>

    </JobBody>

    <JobLocationID>256</JobLocationID>

    <ShowContactInfo>0</ShowContactInfo>

    <ContactCompanyName>RUBA</ContactCompanyName>

    <ContactEmailAddress>

    </ContactEmailAddress>

    <ContactPhoneNumber>

    </ContactPhoneNumber>

    <ContactFaxNumber>

    </ContactFaxNumber>

    <ContactStreetAddress>

    </ContactStreetAddress>

    <ContactCity>

    </ContactCity>

    <ContactState>

    </ContactState>

    <ContactPostalCode>

    </ContactPostalCode>

    <SalaryFrom>0</SalaryFrom>

    <SalaryTo>0</SalaryTo>

    <SalaryTime>0</SalaryTime>

    <JobRefCode>req246</JobRefCode>

    <JobTypeFullTime>1</JobTypeFullTime>

    <JobTypePartTime>0</JobTypePartTime>

    <JobTypeContract>0</JobTypeContract>

    <JobTypePermanent>1</JobTypePermanent>

    <ContactName>

    </ContactName>

    <JobCity>

    </JobCity>

    <JobFunctionID>242</JobFunctionID>

    <JobLevelID>3</JobLevelID>

    <CompanyTurn>

    </CompanyTurn>

    <URLExterno>https://ruba.csod.com/ux/ats/careersite/1/home/requisition/246?c=ruba</URLExterno>

  </AgregarOferta>

  <AgregarOferta>

    <DateExpires>2020-08-24</DateExpires>

    <JobTitle>ANALISTA DE PROCESOS COMERCIAL</JobTitle>

    <JobBody>Elaborar, actualizar, los procesos, políticas, además de brindar el soporte a los usuarios para impulsar un modelo de desarrollo enfocado a la estandarización, mejora continua, sistematización e implementación de los procesos operativos con el objeto de eficientar la operación.</JobBody>

    <JobLocationID>256</JobLocationID>

    <ShowContactInfo>0</ShowContactInfo>

    <ContactCompanyName>RUBA</ContactCompanyName>

    <ContactEmailAddress>

    </ContactEmailAddress>

    <ContactPhoneNumber>

    </ContactPhoneNumber>

    <ContactFaxNumber>

    </ContactFaxNumber>

    <ContactStreetAddress>

    </ContactStreetAddress>

    <ContactCity>

    </ContactCity>

    <ContactState>

    </ContactState>

    <ContactPostalCode>

    </ContactPostalCode>

    <SalaryFrom>0</SalaryFrom>

    <SalaryTo>0</SalaryTo>

    <SalaryTime>0</SalaryTime>

    <JobRefCode>req247</JobRefCode>

    <JobTypeFullTime>1</JobTypeFullTime>

    <JobTypePartTime>0</JobTypePartTime>

    <JobTypeContract>0</JobTypeContract>

    <JobTypePermanent>1</JobTypePermanent>

    <ContactName>

    </ContactName>

    <JobCity>

    </JobCity>

    <JobFunctionID>242</JobFunctionID>

    <JobLevelID>3</JobLevelID>

    <CompanyTurn>

    </CompanyTurn>

    <URLExterno>https://ruba.csod.com/ux/ats/careersite/1/home/requisition/247?c=ruba</URLExterno>

  </AgregarOferta>

</PublicacionOfertas>`

**Comment by Luart125125New** [comment]
Revisando el proceso de FTP y viendo los logs, el cliente ruba, publico de forma exitosa las 3 vacantes:
SUPERVISOR DE CONSTRUCCION DE VIVIENDA,https://www.occ.com.mx/empleo/oferta/13104620,
INGENIERO DE PRUEBAS/QA TESTER,https://www.occ.com.mx/empleo/oferta/13104621,
ANALISTA DE PROCESOS COMERCIAL,https://www.occ.com.mx/empleo/oferta/13104622
El cual se recibió el mismo archivo 3 veces:
27/07/2020 a las 2:00 pm
27/07/2020 a las 3:00 pm
28/07/2020 a las 2:00 am

**Comment by ItzelCervera** [comment]
Cliente comenta que las funciones y los requisitos no se estan publicando, podemos revisar si estan mandando bien la información por favor? o como podemos ayudarlos? @PaLberto21 @Luart125125New

**Comment by Luart125125New** [comment]
Revisando los archivos recibidos por parte del ATS del cliente:

* En la descripción de la vacante nos la están mandando mal (En la documentación esta la forma correcta de como se tiene que enviar para hacer uso correcto del las etiquetas HTML. No esta permitido que el cliente nos manden estilos en las etiquetas ) 
  -Archivo del cliente
![image](https://user-images.githubusercontent.com/53098943/89232475-2250ca80-d5ad-11ea-948d-6ba79792c8d6.png)
  -Descripcion corregida para el uso de etiquetas HTML (En la documentación mostramos otra forma de enviarnos los archivos)
![image](https://user-images.githubusercontent.com/53098943/89336511-20474400-d65f-11ea-8fc6-5ef144bfaba0.png)

*El proceso esta publicando la información que nos esta llegando del cliente. Al parecer la información que esta haciendo mención el cliente  (funciones y los requisitos)  no la esta enviando su ATS correctamente.

*Como observación:  De igual manera para la realización de una acción crear una vacante o dar de baja una vacante, nos están enviando repetidamente 4 archivos con la misma acción en diferentes horas.

**Comment by ItzelCervera** [comment]
@Luart125125New Buenisimo el análisis! Ya se lo envié al cliente y cualquier cosa te aviso pero con esto seguramente le será más fácil identificar el tema.
Muchas gracias!!
