### ISSUE TITLE
Validar direccionamiento PAE

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#141]
Cliente indica que enviaron 1 vacante pero  no se visualiza, cliente tiene webservice

**Comment by Luart125125New** [comment]
Al momento de enviar peticion al WS (a través del método post) se está enviando un carácter especial "&" el cual genera un error de forma automática antes de alcanzar al WS, debido a que ese carácter requiere enviarse de forma codificada ( &amp; )

**Comment by ItzelCervera** [comment]
Muchas gracias!
