### ISSUE TITLE
Favor de generar usuario de direccionamiento webservice xmxprincipalredirx

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#142]
Favor de generar credenciales por webservice xmxprincipalredirx

**Comment by Luart125125New** [comment]
Buenas tardes Itz, acabo de revisar la información de la cuenta en BD y detecte una anormalidad que anterior mente nos a afectado al momento de consumir los créditos. La cuenta xmxprincipalredirx tiene como cuenta administradora a xmxprincipalx y esta a su vez tiene como cuenta administradora xmxprincipalx-001. Básicamente la cuenta de direccionamiento es una sub cuenta de una sub cuenta.
