### ISSUE TITLE
Favor de generar direccionamiento Srapping de Parker de acuerdo a la solicitud por correos xmxparker482redirx

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#143]
https://post.talemetry.com/board_partners/occmexico.cfm?cid=1000010427

Se tomaran datos de la página indicada ya que no es de la principal donde estan todas.

xmxparker482redirx

**Comment by Luart125125New** [comment]
Actualmente en la ruta indicada no hay vacantes disponibles. 
![image](https://user-images.githubusercontent.com/53098943/124832033-a8a22900-df41-11eb-9074-a9eb36bee56e.png)

**Comment by Luart125125New** [comment]
Actualmente la pagina que se nos entrego no cuenta con ninguna vacante para poder probar el proceso, usando la configuración de la vez que se evaluó, fue como se realizo la configuración del Scraper y se creo un PR a la espera, por si se requiere realizar alguna modificación al proceso, estaremos atentos próximas indicaciones. (Su proceso se mantiene en desarrollo hasta que se pueda probar con una vacante en productivo)

**Comment by Luart125125New** [comment]
El día de hoy se nos solicito dar de baja el cliente, la indicación viene directo de contabilidad. 
https://github.com/occmundial/VAPS-Requirements-Bugs/issues/155

**Comment by ItzelCervera** [comment]
gracias!
