### ISSUE TITLE
Favor de validar https://ancabe.orangehrmlive.com/recruitmentApply/3/view

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#146]
validar scrapping

**Comment by Luart125125New** [comment]
Hola Itzel, al momento de revisar la pagina me di cuenta que esta pagina ya había sido evaluada con anterioridad ( https://github.com/occmundial/VAPS-Requirements-Bugs/issues/136 ) se sigue manteniendo las mismas observaciones que la vez pasada, pero en esta ocasión agregándole una mas, ya que actualmente hay una vacante que no cuenta con una descripción de las actividades a realizar o bueno en si no tiene nada (Solo unas etiquetas vacías de html lo cual lo estaríamos enviando a OCC por lo cual al no ser un campo nulo y si se estaría publicando una vacante sin que el cliente vea la descripción de la vacante). Aun que también se pudo visualizar que si puede ser una pagina reciente mente se creo o apenas están publicando vacantes.

**Comment by ItzelCervera** [comment]
ok vamos a recomendar ftp y webservice de primera instancia y si no es viable ya platico de nuevo contigo y vemos que podemos hacer =) mil gracias!!
