### ISSUE TITLE
ORG y RUE-Amedirh Reporta error en la vigencia de vacantes R11

### ISSUE THREAD

**Issue by AngieSM18** [occmundial/VAPS-Requirements-Bugs#15]
Hola chicos muy buen día, 

Les comparto un correo que me envío AMEDIRH , lo que reportan es que las empresas invitadas no pueden cambiar la vigencia de la vacante, y aparece como vacante expirada, este mismo problema me lo reportó la UPQ, en ambos casos les comenté que podrían ellos publicar las vacantes con sus cuentas, con la universidad no hubo mayor tema pero Amedirh que tiene un modo de operar diferente pide alguna solución, de antemano muchas gracias y quedo pendiente de sus comentarios. 

Hola Angelica.
Escale este tema con nuestro contacto en OCC pero desafortunadamente este error sigue persistiendo, te comparto una captura de pantalla donde su muestra el error.
Para agilizar el tema estaré publicando desde la cuenta de AMEDIRH tu vacante esperando no tener esta complicación.
 Angelica Sanchez, me ayudarías por favor a verificar el tema.

![image](https://user-images.githubusercontent.com/67480391/88818644-89711800-d184-11ea-8ef4-d65dfdf39065.png)

**Comment by PaLberto21** [comment]
Nos apoyan a revisar el tema @jzubieta @andr05 muchas gracias

**Comment by AngieSM18** [comment]
Hola chicos @jzubieta  @andr05  @JosueHB , ¿tendremos ya algún avance para comunicarle al cliente?, de antemano muchas gracias.

**Comment by andr05** [comment]
Hola @AngieSM18 estamos dándole una revisada, espero hoy en la tarde tenerte respuesta.

**Comment by PaLberto21** [comment]
@AngieSM18 se revisó el caso, el mensaje de error se debe a que la vacante no pertenece a la cuenta que intenta hacer el cambio de vigencia, se debe ser el owner de la vacante para activarla.
![image](https://user-images.githubusercontent.com/44237843/89327209-2cc4a000-d651-11ea-83b3-21d075da8ef6.png)
