### ISSUE TITLE
Favor de validar scrapping https://iyfglobal.org/work-iyf

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#152]

**Comment by Luart125125New** [comment]
La pagina si se puede scrapear, mi única observación es que la pagina no cuenta con un buen sistema de filtrado, por lo cual cada vez que se scrapea la pagina, se tiene que revisar todas las vacantes de la pagina, con esto se tendría que poner cierto tipo de cuidado con el filtro de localidad ya que hay vacantes de mas países.
La pagina si es apta para el servicio de scrapper, al momento de que se realizo esta evaluación

**Comment by ItzelCervera** [comment]
ok lo comentaré así, muchas gracias!
