### ISSUE TITLE
Favor de validar scrapping https://www.fugadecerebros.mx/jobs

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#153]

**Comment by Luart125125New** [comment]
La pagina si se puede Scrapear, pero al momento de la revisión me percate de varios problemas:
- Al momento de scrappear las vacantes no poseen una URL a la cual podamos redirigir. 
- Revisando su estructura de sus URLS, nosotros podríamos crearlas y de esa manera redirigir a las vacantes, sin embargo aun que la estructura de las URLS es muy simple, hay un detalle que por lo mismo que son muy simples hay URLS que se les anexa un complemento que no existe esa información donde nosotros la podamos y esto es para que no se repita la vacante. 
- No todas las vacantes podrían se scrapeadas debido al problema anterior. 
- En su pagina Web hay publicaciones de vacantes desde el año pasado, por lo cual seria necesario indicar un limitador hasta que fecha quieren que se scrape su pagina para evitar publicar vacantes del año pasado.
Mi recomendación para evitar problemas con el cliente seria que el servicio de scraper no es muy recomendado para el cliente, por los puntos anterior mente mencionados.

**Comment by ItzelCervera** [comment]
Muchas gracias por toda la explicación, ayuda mucho.

De acuerdo con que Scrapping no sea la opción recomendada para ellos.
