### ISSUE TITLE
Favor de revisar problema en FTPS

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#156]

**Comment by Luart125125New** [comment]
El problema solo se presentaría al cliente Santander ya que ellos actualmente cuentan con el servicio de Scrapper por lo cual al momento de que ellos publicaban una vacante desde el SFTP sin designar una fecha de expiración exacta, el WS de forma automática les asignaba un día de vigencia ya que esta configurado para que cada vez que un cliente con el servicio de Scrapper publique una vacante solo se le de un día de vigencia ya que el proceso de scrapper constantemente esta republicando la vacante. 
Además se mejoro el proceso creando un subproceso que elimina los reportes creados a partir de la acciones realizadas por el servicio del SFTP, los reportes que tengan mas de 5 días en línea se eliminaran de forma automática. 
Actualmente los procesos están en revisión se espera que para el día de mañana ya se encuentren en productivo.

**Comment by ItzelCervera** [comment]
Muchas gracias!
