### ISSUE TITLE
Favor de revisar direccionamiento de Pepsico que cliente indica no tener créditos

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#157]

**Comment by Luart125125New** [comment]
Pepsico cuenta con el servicio del WS, el cual todos los mensajes le llegan a ellos directamente. Realice una prueba de su servicio, publicando una vacante de prueba (ya que revisando en BD el cliente cuenta con 2 paquetes activos, solo que uno de ellos ya no cuenta con créditos disponibles, pero el otro si), la prueba resulto de forma exitosa, no se recibió ningún mensaje de error por parte del WS. 
Revisando el correo que nos compartieron se nos indica que el cliente recibió un correo por parte de nosotros, en el cual se le informa que ya no poseen créditos disponibles. Actualmente se desconoce la cuenta que envió el correo (no lo informan en el correo y apenas se le esta preguntando al cliente).
Por la parte del funcionamiento del direccionamiento, es funcional y no presenta fallas.
Estaremos apoyando en la resolución del ticket del cliente para evitar que este inconveniente se presente a otros clientes. 
Actualmente estamos a la espera de la cuenta que envió el correo para poder identificar el proceso y apoyar tanto en su revisión como en su solución.

**Comment by Luart125125New** [comment]
Notas extra: 
- Se regreso el crédito usado en la prueba realizada.
- Revisando el historial de publicaciones  del cliente, no se ha detectado alguna anormalidad y su ultima publicación fue realizada el 2021-07-28, un día antes de que se me notificara del mensaje atreves del correo. Como objeto de prueba valdría la pena realizar una publicación por parte de ellos para ver si el mensaje se vuelve a presentar. 
Quedo atento a cualquier comentario. 
Saludos.

**Comment by ItzelCervera** [comment]
Muchas gracias!
