### ISSUE TITLE
Favor de validar scrapping https://careers.vontier.com/us/en/search-results

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#159]
https://careers.vontier.com/us/en/search-results

**Comment by Luart125125New** [comment]
La pagina si se puede scrappear y usaríamos la siguiente url https://careers.vontier.com/us/en/search-results?qstate=Mexico&qcountry=North%20America para poder aprovechar su propio buscador y filtrar las vacantes que solo son de México,

**Comment by ItzelCervera** [comment]
gracias!
