### ISSUE TITLE
Favor de validar scrapping de https://jobs.sutherlandglobal.com/?lang=en

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#161]

**Comment by Luart125125New** [comment]
La pagina si se puede scrappear y usaríamos la siguiente url https://jobs.sutherlandglobal.com/listjobs/All/search/Country/MX/?lang=en para poder aprovechar su propio buscador y filtrar las vacantes que solo son de México.

**Comment by ItzelCervera** [comment]
gracias!
