### ISSUE TITLE
Favor de activar direccionamiento por Equest de cliente nuevo Universidad Rioja

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#2]
Por favor nos apoyas con el alta de direccionamiento por Equest de este cliente por favor? xmxuniversid337redir @PaLberto21 @Luart125125New

**Comment by Luart125125New** [comment]
Listo, el cliente ya esta activo en el proceso eQuest.

**Comment by ItzelCervera** [comment]
Gracias
