### ISSUE TITLE
Favor de revisar reporte del cliente que no ha podido publicar en direccionamiento Campari

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#23]
"
![unnamed (1)1](https://user-images.githubusercontent.com/67603333/89592938-7eb52380-d813-11ea-8e33-f3c433e93fdd.png)
Hemos posteado 2 posiciones dentro de la plataforma, la primera me permitió realizarlo sin embargo en estatus se quedó Processing.. al parecer no había ninguna implicación con esto.Pero hace unos momentos intenté publicar otra posición y me arroja el siguiente error, me puedes ayudar a revisar si es algo que se tiene que cambiar de su lado "

**Comment by PaLberto21** [comment]
@ItzelCervera revisamos el caso, sin embargo, es importante recordar que no tenemos manera de saber cual es la contraseña, recuerda que se aplicó una corrección por temas de seguridad y ya no hay manera de saberlas, y aplica para todos los usuarios de OCC

**Comment by ItzelCervera** [comment]
@PaLberto21 todas las aplicaciones de ATS les solicitan usuarios y contraseñas, en este caso que contraseña se le debe indicar que es o como obtenerla?

Si me gustaria que se pudiera saber sino la contraseña, el.proceso de obtencion para que se haga como parte del proceso del cliente.

De este caso en especifico se me hace raro que si pofian mandar todo y ahorita les salga error de contraseña.

**Comment by Luart125125New** [comment]
@PaLberto21  y @ItzelCervera el direccionamiento que tiene **Campari**  es FTP por lo cual las personas de infra son las que nos generan las contraseñas, esas contraseñas nosotros ni el cliente las puede modificar. Revise en el hisorial de mensajes que tenemos sobre ese cliente y realice una prueba para validar sus credenciales y funciona correctamente.
![image](https://user-images.githubusercontent.com/53098943/89931198-825cf780-dbd1-11ea-8f8f-7b5893ecabe6.png)
No hay problema por parte de sus credenciales.

**Comment by Luart125125New** [comment]
Revisando su documentación procesada, ellos nos siguen enviando sus archivos de forma normal (vacíos). 
![image](https://user-images.githubusercontent.com/53098943/89932549-6eb29080-dbd3-11ea-8ea1-259d8d598e5b.png)

**Comment by ItzelCervera** [comment]
Gracias por el análisis @Luart125125New le comento al cliente
