### ISSUE TITLE
Reporte diario de direccionamiento de no créditos no esta llegando de todos los clientes

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#25]
No llega el reporte de Draex, xmxproyeccio13387red,

**Comment by Jopuca** [comment]
@ItzelCervera no llega el correo al ejecutivo porque, aunque en el administrador de reportes se ven las cuentas que tienen 0 elementos disponibles, con un 'Paquete Activo' o que están 'Sin Paquete', en el envío de email solo se está haciendo para los 'Paquete Activo'. Ya modifiqué la tarea del envío por email para que también lo haga cuando el estatus es 'Sin Paquete'

**Comment by ItzelCervera** [comment]
Muchas gracias @Jopuca !!
