### ISSUE TITLE
Favor de validar scrapping https://www.oportunidadesdhl.com/

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#26]
Buenas tardes, me ayudarían a validar el scrapping de este cliente por favor?

https://www.oportunidadesdhl.com/

**Comment by MitziMtz** [comment]
Hola @PaLberto21 , @ItzelCervera se validó la página y es factible por scraping

**Comment by ItzelCervera** [comment]
Mil gracias @MitziMtz  =)
