### ISSUE TITLE
Favor de activar las vacantes de direccionamiento de P&G que el cliente desactivo por accidente.

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#28]
Buenos días, 
El cliente de P&G xmxnetwork7282x nos solicita activar las vacantes que desactivaron por accidente, aún tienen vigencia, por lo que sería activarlas solamente no republicarlas para no consumir otro crédito.
![unnamed (1)](https://user-images.githubusercontent.com/67603333/90648296-f2d1cd00-e1fe-11ea-9071-d0aa3a3543f4.png)

**Comment by MitziMtz** [comment]
@ItzelCervera ya se activaron las vacantes :)

**Comment by ItzelCervera** [comment]
Muchas gracias!!!
