### ISSUE TITLE
ORG- Amedirh- problema de empresa invitada para visualizar CV

### ISSUE THREAD

**Issue by AngieSM18** [occmundial/VAPS-Requirements-Bugs#29]
Muy buenos días equipo, Amedirh me reporta que la subcuenta xmxamedirhx-474 le reporta los siguientes CV que no puede revisar:

![image](https://user-images.githubusercontent.com/67480391/91187376-b8ac7380-e6b5-11ea-9714-1ba66bcb802b.png)

El tema es que estas cuentas no deberían de poder recibir postulaciones sólo de la gente que se loguea en la bolsa, ¿Desde dónde se postuló el candidato? quedo pendiente, saludos y muchas gracias.

**Comment by AngieSM18** [comment]
Hola @PaLberto21 , te comentó que Amedirh me comparte que con la vacante 13144951 que él publicó con su cuenta xmxamedirhx, también le llegó una postulación que no puede ver, el ID del CV es 2808842

![image](https://user-images.githubusercontent.com/67480391/91315111-e4def780-e77c-11ea-800d-5d891ec4bd9c.png)

¿Me apoyas por fa a trasladarlo a quien corresponda por fis? necesito brindarle alguna razón al cliente. De antemano muchas gracias por el apoyo y quedo pendiente, saludos.

**Comment by AngieSM18** [comment]
@PaLberto21 me pregunta el cliente alguna respuesta al problema, ¿me podrían apoyar por favor?

**Comment by PaLberto21** [comment]
@marcoogalicia nos ayudarias a darle seguimiento a este tema, por fa si hay algo en lo que pueda apoyar notifícame, muchas gracias!

**Comment by marcoogalicia** [comment]
Revisare el caso y en cuento tenga algo se los comunicare.

**Comment by AngieSM18** [comment]
![image](https://user-images.githubusercontent.com/67480391/94314074-750f8880-ff45-11ea-82cd-f28a338fddb3.png)
ID de CV: 10838936

**Comment by AngieSM18** [comment]
ID de CV: 10755679
![image](https://user-images.githubusercontent.com/67480391/94574889-3e818880-0239-11eb-8afb-0ca8349f0821.png)

ID de CV:2149384
![image](https://user-images.githubusercontent.com/67480391/94574969-56f1a300-0239-11eb-8f09-cb3b6afcb863.png)

**Comment by blancavg** [comment]
Hola Angie,
Revisaremos si proviene de recomendaciones y te informamos

**Comment by blancavg** [comment]
Hola @AngieSM18 ,
@yoshicam  identificó que faltaba un filtro por lo que en los correos asociados podían ir vacantes de la RUE . Ya puso en producción el cambio y al menos por recomendaciones ya no van vacantes de la RUE.

**Comment by AngieSM18** [comment]
@blancavg  @yoshicam ¿también aplican las de bolsas ORG?
