### ISSUE TITLE
Cliente con direccionamiento xmxnetwork7282redirx requiere contraseña del direccionamiento por favor

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#30]
@PaLberto21

**Comment by PaLberto21** [comment]
@Luart125125New se acordó con @ItzelCervera que te facilitaría las credenciales de la cuenta administradora para hacer una prueba y saber si concretamente la contraseña era la misma para la cuenta de direccionamiento, hay algún avance con este tema? gracias

**Comment by ItzelCervera** [comment]
De hecho ya quedo, ya reseteamos la contraseña =)
