### ISSUE TITLE
Favor de activar direccionamiento webservice xmxgivaudanredirx

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#33]
Grupo Givaudan SA de CV.

https://www.givaudan.com/

**Comment by Luart125125New** [comment]
@ItzelCervera y @PaLberto21 su proceso de direccionamiento ya esta activo y se realizo una prueba creando una vacante https://www.occ.com.mx/empleo/oferta/13165262
Respecto a su contraseña yo no puedo visualizarla.

**Comment by ItzelCervera** [comment]
Muchas gracias @Luart125125New
