### ISSUE TITLE
Favor de validar estatus de vacantes de Leoni que cliente comenta que no se estan visualizando en OCC

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#34]

**Comment by Luart125125New** [comment]
Ya revise su información @ItzelCervera, su proceso trabaja de forma correcta solo que la cuenta no tiene créditos. 
![image](https://user-images.githubusercontent.com/53098943/92420454-fa6afe80-f138-11ea-841d-575f214859c8.png)

**Comment by Luart125125New** [comment]
![image](https://user-images.githubusercontent.com/53098943/92420526-7d8c5480-f139-11ea-9a18-6907c530a2f6.png)

**Comment by ItzelCervera** [comment]
Gracias @Luart125125New !
