### ISSUE TITLE
Favor de validar scrapping https://shield-geo.breezy.hr/

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#36]

**Comment by MitziMtz** [comment]
@ItzelCervera ya se validó la pagina, es factible para scraping. 
![Captura](https://user-images.githubusercontent.com/55200945/92528207-fcdb6000-f1ed-11ea-9287-65ef94e0ed0f.PNG)
Solo como comentario las vacantes no son de un lugar en especifico, indican que son de varios países, incluidos México y en las descripciones encontramos unos Links que se quitarían en el proceso.

**Comment by ItzelCervera** [comment]
Gracias @MitziMtz si, serían solo las de México, gracias!
