### ISSUE TITLE
Favor de revisar direccionamiento xmxunitecredirx

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#38]
El cliente esta indicando que si ha mandado vacantes despues de marzo de este año y en el reporte que se le manda semanalmente no se ven estas, nos pide una revisión y asegurar que si se esten publicando sus vacantes por lo que necesitamos una revisión de lo que ha publicado por medio del webservice esta cuenta en este año.
En su momento tenían la cuenta xmxunitecredir2x favor de revisar esta cuenta, no se si sea ese el tema que se esten publicando con ella y no tengamos el reporte.

@Luart125125New @MitziMtz

**Comment by Luart125125New** [comment]
https://docs.google.com/spreadsheets/d/12e6PP9Um4efpc4DoeD80EBThnD9_wGLLUMTjWhVl1E4/edit?usp=sharing

**Comment by ItzelCervera** [comment]
gracias
