### ISSUE TITLE
Favor de validar el formato de las vacantes de Draex

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#44]
https://www.occ.com.mx/empleo/oferta/13215611-production-leader-50961587?ai=false&origin=unknown&page=1&rank=1&returnURL=%2Fempleos%2Fde-13215611%2F%231&sessionid=dbb9641d-5866-416b-9ba5-1d8793fffe0b&showseo=true&type=0&userid=&utm_channel=serp&utm_origin=web&uuid=d73062f7-a833-46cc-9129-5a2c1a74d9cb

@Luart125125New @MitziMtz

**Comment by Luart125125New** [comment]
La forma por la que la vemos de esa manera es porque en la descripción no nos están mandando ningún tipo de etiqueta HTML como se muestran en la guía y al momento que se procesa la información se codifica la descripción para publicarla en OCC. 
![image](https://user-images.githubusercontent.com/53098943/95526824-414b4e80-099a-11eb-850a-d74a996a211a.png)

**Comment by ItzelCervera** [comment]
Gracias!
