### ISSUE TITLE
Favor de evaluar scrapping

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#45]
google.com/url?q=http://careers.tmf-group.com/cw/en/filter/?search-keyword%3D%26location%3Dmexico%26job-mail-subscribe-privacy%3Dagree&sa=D&source=hangouts&ust=1602287149413000&usg=AFQjCNEgXQ-_sFOCF-_cwXKFA5trXfaJFQ

**Comment by MitziMtz** [comment]
Hola @ItzelCervera , ya se validó la página y es factible para scraping

**Comment by ItzelCervera** [comment]
Gracias @MitziMtz !
