### ISSUE TITLE
Favor de validar Scrapping de https://mi.empleonaps.com/

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#49]

**Comment by MitziMtz** [comment]
@ItzelCervera Ya lo validé y es factible para Scraping, solo como comentario en algunas vacantes no se especifica la ubicación (Tiene el nombre de la empresa) y se le pueden dar dos opciones al cliente, que se les designe a todo México o que se omitan.

**Comment by ItzelCervera** [comment]
muchas gracias!
