### ISSUE TITLE
Cliente de Campari reporta que se envío vacante por FTP y no esta publicada

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#6]
![Screenshot (123)](https://user-images.githubusercontent.com/67603333/87321831-55de8e80-c4f2-11ea-897d-64c05b2ca2fc.png)

**Comment by PaLberto21** [comment]
@Luart125125New @MitziMtz nos apoyan a revisar el caso, porfa, muchas gracias

**Comment by Luart125125New** [comment]
@ItzelCervera todos sus archivos que hemos recibido por parte de ellos, se ha procesado correctamente. Todos sus archivos recibidos hasta el momento están vacíos, le puedes comentar al cliente que nos reenvie el archivo y nos diga el día que nos enviara el archivo.

**Comment by ItzelCervera** [comment]
Gracias @Luart125125New Le comento al cliente y te copio.
