### ISSUE TITLE
Favor de validar scrapping de https://www.fleetcomplete.com/es/join-the-team/ 

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#62]

**Comment by MitziMtz** [comment]
Hola @ItzelCervera la página cuenta con iframes en la sección de las vacantes por lo que no podemos extraer esa información, por lo tanto no es factible para hacer scraping

**Comment by ItzelCervera** [comment]
Gracias!
