### ISSUE TITLE
El cliente de ICONN nos solicita apoyo para que puedan implementar el direccionamiento contratado.

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#7]
Buenas tardes, el cliente nos escribió lo siguiente:
"La gente de infraestructura nos pide el rango de IP’s, las cuales puede responder la pagina de servicios de OCC http://wsrecluta105.occmundial.com/, con el fin de no tener problemas para el acceso a sus servicios No importa si son 100, 200, etc de  numero de IP’s, pero si las necesitamos para darlas de alta en el firewall."

Miki, me menciona lo siguiente del tema: ""al parecer puede ser una cuestion de su red de ellos que no tienen acceso a todo lo externo por internet, por sus politicas de red. Esta cuestión se tiene que ver con infraestructura. Mi recomendación de como puedes proseguir:
Primero responderles que te pondras en comunicación con nuestro equipo de infra para que de nuestro lado proporcionarles la información solicitada, y que si mientras pueden validar que efectivamente no puedan visualizar este contrato  http://wsrecluta105.occmundial.com/OCCMService.asmx
  2, Contacta a Samuel, platicale el caso de la "Empresa que quiere consumir el webservice expuesto en http://wsrecluta105.occmundial.com/ y que    comentan que necesitan las IPs porque no pueden alcanzar el servicio".
Esto para verificar si infra puede soltar los datos de IPs sin ningun problema, o hay algo mas que verificar.
Porque resulta que a lo mejor nosotros debemos tener su IPs en nuestra white list, si les soltamos las IPs necesitamos que nos den su origen para saber que efectivamente son ellos."

Por lo que solicitaría de su apoyo para revisar con Infra o quien corresponda el tema para responder al cliente ya que al ser un tema técnico me gustaría que pudieran guiarnos al respecto.
Gracias,

@PaLberto21 @Areli13

**Comment by PaLberto21** [comment]
Se le solicito la información al equipo de Infra, tan pronto se proporcione, les informamos.

**Comment by ItzelCervera** [comment]
Gracias @PaLberto21 Sabes el tiempo de respuesta, urge mucho al cliente, ya ha enviado varias solicitudes, ¿Podrían revisar con @samuelrojasm o con quien se haya reportado por favor?

**Comment by PaLberto21** [comment]
La IP que debe registrar el cliente es 216.136.116.29   
lo que se traduce al siguiente link  http://216.136.116.29/OCCMService.asmx

**Comment by ItzelCervera** [comment]
Gracias
