### ISSUE TITLE
Favor de realizar el whitelist de la IP address 13.85.47.21 para el FTP de Smyflash por favor

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#73]

**Comment by PaLberto21** [comment]
@ItzelCervera no es necesario agregar la IP del cliente a nuestra Whitelist, ya que es un recurso que esta alcanzable de manera abierta, quizas ellos si deban agregar la IP de nuestro servidor de FTP

**Comment by ItzelCervera** [comment]
ok muchas gracias Pablo! Lo menciono al ATS
