### ISSUE TITLE
Favor de validar scrapping https://www.bullhorn.com/products/bullhorn-for-salesforce/

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#79]
Es el nuevo ATS de Manpower y aun no tienen vacantes pero quieren que vayamos investigandolos, ¿Por favor nos podrían dar su opinión?

**Comment by Luart125125New** [comment]
La url que nos compartiste no presenta ningún problema para scrapearla pero hasta que no podamos ver la lista de vacantes no podremos asegurar el scraper.

**Comment by ItzelCervera** [comment]
Gracias!
