### ISSUE TITLE
Favor de desactivar direccionamientos de prueba sin uso.

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#82]
Se detectan que las siguientes cuentas no se han ocupado de pruebas y siguen activas, favor de desactivarlas o si alguna se desea dejar activa favor de indicarlo, de lo contrario favor de proceder con desactivacion.
tasklinkoutscraping@occ.com.mx  xmxtasklinkoutsredir	
Proceso de direccionamiento por ftp xmxproceso54908redir		
OCCMundial xmxpruebas572x-001
Empleolisto xmxempleolistoredirx		(Se reviso con Adal y se solicita desactiació también)
ACTIVACIONES DR141120fff xmxileanaprbsredirx	
Empresa Líder en Lubricantes xmxempresa232redirx
Activaciones Pruebas DR xmxactivacio0137redi		
@PaLberto21 @gmatehuala @Luart125125New @MitziMtz

**Comment by Luart125125New** [comment]
Después de revisar el estado actual de las cuentas, las únicas cuentas que se optaron por dejarlas activas son las siguientes: 
- xmxproceso54908redir
- xmxtasklinkoutsredir
- xmxactivacio0137redi
Las cuentas que no fueron seleccionadas se procederán a desactivar.

**Comment by ItzelCervera** [comment]
Gracias!
