### ISSUE TITLE
Favor de desarrollar scrapping de axalta xmxaxaltaredirx

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#83]

**Comment by Luart125125New** [comment]
El proceso para el scrapper ya fue finalizado, pero para poder subir las actualizaciones del cliente a productivo, tenemos que esperarnos al equipo de calypso (un API) para que nos designen el endpoint del clienten. Cuando lo designen subiremos el PR a productivo.

**Comment by ItzelCervera** [comment]
Gracias

**Comment by Luart125125New** [comment]
El endpoint se nos acaba de entregar, en el transcurso del día de mañana estaremos subiendo los cambios a productivo.

**Comment by ItzelCervera** [comment]
Gracias!
