### ISSUE TITLE
Favor de generar direccionamiento scrapping web xmxball153redirx

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#84]
https://jobs.ball.com/corp_packaging/?utm_source=careersite&utm_campaign=candpsearchhere&_ga=2.32772022.92696251.1610661442-1212581921.1598972492

**Comment by Luart125125New** [comment]
El proceso para el scrapper ya fue finalizado, pero para poder subir las actualizaciones del cliente a productivo, tenemos que esperarnos al equipo de calypso (un API) para que nos designen el endpoint del clienten. Cuando lo designen subiremos el PR a productivo.

**Comment by ItzelCervera** [comment]
ok favor de notificarme cuando quede para avisar al cliente por favor. @Luart125125New

**Comment by Luart125125New** [comment]
El endpoint se nos acaba de entregar, en el transcurso del día de mañana estaremos subiendo los cambios a productivo.

**Comment by ItzelCervera** [comment]
Gracias!
