### ISSUE TITLE
Favor de desarrollar direccionamiento scrapping para Bosch

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#85]
El cliente hace tiempo tenía direccionamiento por webservice, esta ocasión contrato de nuevo pero scrapping.

Robert Bosch México S.A. de C.V.
Vigencia: 26/01/2021 al 26/01/2022
Scrapping
xmxboschrredirx
https://careers.smartrecruiters.com/BoschGroup/mexico

**Comment by Luart125125New** [comment]
Ya esta en productivo.
