### ISSUE TITLE
Favor de generar credenciales de Webservice para Hella  xmxgrupo574585redirx

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#89]

**Comment by Luart125125New** [comment]
Se realizo una revisión del estado de la cuenta, la cuenta al día de hoy es funcional y como medida de prueba se realizo una publicación de una vacante siendo esta de publicada de forma exitosa. 
https://www.occ.com.mx/empleo/oferta/13479001

**Comment by Luart125125New** [comment]
PD. Por mediadas de seguridad yo no tengo acceso a la contraseña del cliente.

**Comment by ItzelCervera** [comment]
Gracias!
