### ISSUE TITLE
Favor de revisar direccionamiento de Draex donde el formato no ha quedado correcto.

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#90]

**Comment by Luart125125New** [comment]
Se había presentando una anormalidad al momento de encodear el texto, se implemento un cambio para que las vacantes se puedan visualizar sin ningún problema, se realizaran mas pruebas para confirmar que este fallo no se presente en un futuro próximo.

**Comment by ItzelCervera** [comment]
gracias
