### ISSUE TITLE
Favor de desactivar direccionamiento xmxsdvredirx por no renovación

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#94]
Favor de desactivar direccionamiento xmxsdvredirx por no renovación

**Comment by Luart125125New** [comment]
La vacante ya se encontraba desactivada.

**Comment by ItzelCervera** [comment]
Me imagino que te refieres a la cuenta de direccionamiento, no a una vacante verdad?

**Comment by Luart125125New** [comment]
Perdón es la costumbre, así es, la cuenta de direccionamiento ya estaba desactivada.

**Comment by ItzelCervera** [comment]
Mil gracias!!!
