### ISSUE TITLE
Favor de validar  ligahttps://jobsdata.smashfly.com/fulljobfeed/smashfly.xml

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#96]
un cliente va a contratar direccionamiento, ellos tienes Smashfly y nos mandaron esta ligahttps://jobsdata.smashfly.com/fulljobfeed/smashfly.xml.

Me apoyan con la validación por favor?

**Comment by Luart125125New** [comment]
Si se puede scrapear, se puede dar seguimiento con el ticket (https://github.com/occmundial/VAPS-Requirements-Bugs/issues/108)

**Comment by ItzelCervera** [comment]
gracias!
