### ISSUE TITLE
Generar direccionamiento Arrow

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#97]
EL cliente de ARrow ya adiquirio el direccionamiento, serán todas las vacantes premium por lo que debe estar automatizado que no sea necesario colocar ninguna clave.
URL:  https://careers.arrow.com/us/en  
xmxelectroiaredirx

**Comment by MitziMtz** [comment]
El proceso ya se encuentra funcional

**Comment by ItzelCervera** [comment]
Muchas gracias MItzi!!!
