### ISSUE TITLE
Favor de revisar direccionamiento de Michael Page que cliente indica que no esta corriendo adecuadamente.

### ISSUE THREAD

**Issue by ItzelCervera** [occmundial/VAPS-Requirements-Bugs#98]
Favor de revisar direccionamiento de Michael Page que cliente indica que no esta corriendo adecuadamente.

**Comment by Luart125125New** [comment]
La cuenta de direccionamiento **xmx1mpageredirx** esta actualmente desactivada, en su petición el campo (LogoCuenta) están ingresando esa cuenta, cuando deberían de usar **xmxppersonnelredirx** en la vacante que si se logro publicar usan la cuenta adecuada. Solo hay que comentarles que la cuenta **xmx1mpageredirx** ya esta desactivada y que tienen que usar la cuenta **xmxppersonnelredirx** para publicar en occ.
Tengo una petición realizada el 11 de enero solicitando la desactivación de la cuenta xmx1mpageredirx.

**Comment by ItzelCervera** [comment]
mil gracias!!
